name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 195.200.3.176
          username: u947842261
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            cd ~/domains/heltoniwilson.com.br/public_html/ozonteck
            git pull origin main
